update CoC Contributing Readme logo
deepgram-devs/deepgram-cli pull request #128
Opened 2023-07-14 00:11 UTC by jpvajda

- uses our standard logo svg
- updated code of conduct reference 
- adds a contributing guide
- updates readme to our new standards.

2023-07-14 14:56 UTC, lukeocodes requested changes

2023-07-25 22:30 UTC, jpvajda commented
I'm checking with @lukeocodes  if this can be merged in.

2023-07-26 16:52 UTC, jpvajda commented on README.md
> +* [Contributors](#contributors)
I have a TOC plugin that looks for syntax like <!-- usagestop --> and thinks a TOC should be used here 🙄  I removed the TOC and this should be good now.

2023-07-26 17:51 UTC, lukeocodes approved these changes

2023-07-26 17:55 UTC, merged